routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@welcome')->name('welcome');

Route::get('/how-it-works', function () {
    return view('how-it-works');
})->name('how-it-works');

Route::get('/contact', function () {
    return view('contact');
})->name('contact');

Auth::routes();


Route::get('companies', 'CompanyController@index')->name('companies');
Route::get('companies/{company}', 'CompanyController@show')->name('companies.show');
Route::get('/download/{uuid}', 'MediaController@download')->name('download');


Route::resource('jobs','FrontJobsController');
Route::resource('users', 'FrontUsersController');

Route::get('fr', function() {
    cookie()->forever('locale','fr');
    return redirect()->back()->cookie('locale', 'fr', 5256000);
});

Route::get('en', function() {
    return redirect()->back()->cookie('locale', 'en', 5256000);
});

Route::get('lang/{key}', function ($key) {
   return Lang::get('components.'.$key);
});


Route::middleware('auth')->prefix('dashboard')->name('dashboard.')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/settings', 'UserController@account')->name('settings');
    Route::get('/settings/password', 'UserController@password')->name('settings.password');
    Route::put('/settings', 'UserController@update')->name('settings.update');
    Route::put('/settings/password', 'UserController@updatePassword')->name('settings.password.update');
    Route::post('/settings/attachments', 'UserController@uploadAttachment')->name('settings.upload');
    Route::delete('/settings/attachments/{uuid}', 'UserController@removeAttachment')->name('attachments.remove');


    Route::resource('jobs','JobController')->middleware('type:employer');
    Route::post('jobs/attachments/temp','JobController@tempAttachments')->name('jobs.attachments.temp');
    Route::post('jobs/{id}/attachments/temp','JobController@addAttachments')->name('jobs.attachments.add');
    Route::delete('jobs/attachments/delete/{uuid}','JobController@removeAttachment')->name('jobs.attachments.delete');

    Route::get('jobs/{job}/candidates','JobController@candidates')->name('jobs.candidates');
    Route::get('jobs/{job}/candidates/{candidate}','JobController@showCandidates')->name('jobs.candidates.show');
    Route::delete('jobs/{job}/candidates/{candidate}','JobController@deleteCandidates')->name('jobs.candidates.destroy');

    Route::resource('candidates', 'CandidateController')->middleware('type:freelancer');

    Route::post('candidates/{id}/attachments/temp','CandidateController@addAttachments')->name('candidates.attachments.add');
    Route::delete('candidates/attachments/delete/{uuid}','CandidateController@removeAttachment')->name('candidates.attachments.delete');

    Route::resource('bookmarks', 'BookmarkController');
});

app/Job.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

/**
 * App\Job
 *
 * @property int $id
 * @property string $title
 * @property string $type
 * @property string $category
 * @property string|null $location
 * @property float|null $lng
 * @property float|null $lat
 * @property int|null $map_zoom
 * @property int|null $salary_min
 * @property int|null $salary_max
 * @property array|null $tags
 * @property string $description
 * @property int $user_id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Bookmark[] $bookmarks
 * @property-read int|null $bookmarks_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Candidate[] $candidates
 * @property-read int|null $candidates_count
 * @property-read \App\User $company
 * @property-read \Spatie\MediaLibrary\MediaCollections\Models\Collections\MediaCollection|\Spatie\MediaLibrary\MediaCollections\Models\Media[] $media
 * @property-read int|null $media_count
 * @method static \Illuminate\Database\Eloquent\Builder|Job newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Job newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Job query()
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereCategory($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereLat($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereLng($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereLocation($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereMapZoom($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereSalaryMax($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereSalaryMin($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereTags($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereType($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereUserId($value)
 * @mixin \Eloquent
 */
class Job extends Model implements HasMedia
{

    use InteractsWithMedia;

    protected $fillable = [
        'title',
        'type',
        'category',
        'location',
        'lat',
        'lng',
        'map_zoom',
        'salary_min',
        'salary_max',
        'tags',
        'description',
        'user_id',
    ];

    protected $casts = [
        'tags' => 'array',
        'lat' => 'double',
        'lng' => 'double',
        'map_zoom' => 'integer'
    ];

    public function company(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function similarJobs()
    {
        return Job::where('id', '<>', $this->id)
            ->where('category', $this->category)
            ->limit(2)
            ->get();
    }

    public function candidates(): HasMany
    {
        return $this->hasMany(Candidate::class);
    }

    public function bookmarks(): HasMany
    {
        return $this->hasMany(Bookmark::class);
    }

    public function bookmark()
    {
        return $this->bookmarks()->where('user_id', \Auth::id())
            ->limit(1)->first();
    }

    public static function customSearchQuery(array $params)
    {
        $query = Job::getQuery();

        if (key_exists('lat', $params) and
            key_exists('lng', $params) and
            key_exists('distance', $params) and
            key_exists('location', $params) and
            $params['lat'] and
            $params['lng'] and
            $params['distance'] and
            $params['location']
        ) {
            $lat = $params['lat'];
            $lng = $params['lng'];
            $distance = $params['distance'];

            $query = $query->whereRaw('lat BETWEEN ( ? - ( ? * 0.0117)) AND ( ? + ( ? * 0.0117))', [$lat, $distance, $lat, $distance]);
            $query = $query->whereRaw('lng BETWEEN ( ? - ( ? * 0.0117)) AND ( ? + ( ? * 0.0117))', [$lng, $distance, $lng, $distance]);
        }

        if (key_exists('keywords', $params) and $params['keywords']) {
            $keywords = explode(',', $params['keywords']);
            if (count($keywords)) {
                $query = $query->whereRaw('MATCH (title ,description) AGAINST (?)', $keywords);
            }
        }

        if (key_exists('salary', $params)) {
            $salary = explode(',', $params['salary']);
            $query = $query
                ->where('salary_min', '<=', $salary[1])
                ->where('salary_max', '>=', $salary[0]);
        }

        if (key_exists('categories', $params)) {
            $categoriesSearch = $params['categories'];
            if (count($categoriesSearch)) {
                $query = $query->whereIn('category', $categoriesSearch);
            }
        }

        if (key_exists('types', $params)) {
            $typesSearch = $params['types'];
            if (count($typesSearch)) {
                $query = $query->whereIn('type', $typesSearch);
            }
        }

        return $query;
    }
}

app/Http/Controllers/JobController.php
<?php

namespace App\Http\Controllers;

use App\Candidate;
use App\Job;
use App\User;
use Auth;
use Illuminate\Http\Request;
use Spatie\MediaLibrary\MediaCollections\Exceptions\FileDoesNotExist;
use Spatie\MediaLibrary\MediaCollections\Exceptions\FileIsTooBig;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class JobController extends Controller
{
    public function index()
    {
        $jobs = Auth::user()->jobs;
        return view('dashboard.jobs.index', compact('jobs'));
    }

    public function create()
    {
        return view('dashboard.jobs.create');
    }


    public function store(Request $request)
    {
        $validated_data = $request->validate([
            'title' => 'required|string',
            'type' => 'required|string',
            'category' => 'required|string',
            'location' => 'nullable|string',
            'lat' => 'nullable|string',
            'lng' => 'nullable|string',
            'map_zoom' => 'nullable|string',
            'salary_min' => 'nullable|string',
            'salary_max' => 'nullable|string',
            'tags' => 'nullable|string',
            'description' => 'required|string',
        ]);

        $user = User::find(Auth::id());

        $validated_data["tags"] = explode(',', $validated_data["tags"]);

        $job = Auth::user()->jobs()->create($validated_data);

        foreach ($user->getMedia('tempJobsAttachments') as $media) {
            $media->copy($job, 'attachments');
            $media->delete();
        }

        return redirect()->route('dashboard.jobs.edit', $job->id)->with('message', 'job created successfully');
    }


    public function show(Job $job)
    {
        $job->getMedia();
        return $job;
    }


    public function edit(Job $job)
    {
        return view('dashboard.jobs.edit', compact('job'));
    }


    public function update(Request $request, Job $job)
    {
        $validated_data = $request->validate([
            'title' => 'required|string',
            'type' => 'required|string',
            'category' => 'required|string',
            'location' => 'nullable|string',
            'lat' => 'nullable|string',
            'lng' => 'nullable|string',
            'map_zoom' => 'nullable|string',
            'salary_min' => 'nullable|string',
            'salary_max' => 'nullable|string',
            'tags' => 'nullable|string',
            'description' => 'required|string',
        ]);

        $validated_data["tags"] = explode(',', $validated_data["tags"]);

        $job->update($validated_data);

        return redirect()->route('dashboard.jobs.edit', $job->id)
            ->with('message', 'job updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Job $job
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Job $job)
    {
        try {
            Auth::user()->jobs()->findOrFail($job->id)->delete();
            return redirect()->back()->with('message', 'job deleted');
        } catch (\Exception $e) {
            throw $e;
        }
    }

    public function tempAttachments(Request $request)
    {
        $user = User::find(Auth::id());
        try {
            $file = $user->addMediaFromRequest('file')
                ->toMediaCollection('tempJobsAttachments');
            return response()->json($file);
        } catch (FileDoesNotExist $e) {
        } catch (FileIsTooBig $e) {
        }
        return null;
    }

    public function addAttachments($id, Request $request)
    {
        $user = User::find(Auth::id());
        $job = $user->jobs->find($id);
        try {
            $file = $job->addMediaFromRequest('file')
                ->toMediaCollection('attachments');
            return response()->json($file);
        } catch (FileDoesNotExist $e) {
        } catch (FileIsTooBig $e) {
        }
        return null;
    }

    public function removeAttachment($uuid)
    {
        $media = Media::findByUuid($uuid);
        $user = User::find(Auth::id());

        try {
            if ($user->jobs->find($media->getAttribute('model_id')))
                if ($media->delete())
                    return response()->noContent();
            return 'nop!';
        } catch (\Exception $e) {
        }

        return null;
    }

    public function candidates(Job $job) {
        return view('dashboard.jobs.candidates.index', compact('job'));
    }

    public function showCandidates(Job $job, Candidate $candidate) {

        $user = $candidate->user;
        return view('dashboard.jobs.candidates.show', compact('job','candidate', 'user'));
    }

    public function deleteCandidates(Job $job, Candidate $candidate) {
        Auth::user()->jobs()->findOrFail($job->id);
        $job->candidates()->findOrFail($candidate->id);
        try {
            $candidate->delete();
            return redirect()->back()->with('message', 'candidate deleted');
        } catch (\Exception $e) {
        }
    }
}

resources/views/dashboard/jobs/create.blade.php
@extends('layouts.dashboard')

@section('content')
    <!-- Dashboard Headline -->
    <div class="dashboard-headline">
        <h3>{{ __('dashboard.settings.jobs.create.Post a Job') }}</h3>
        {{ env('APP_NAME') }}

        <!-- Breadcrumbs -->
        <nav id="breadcrumbs" class="dark">
            <ul>
                <li><a href="{{ route('dashboard.home') }}">{{ __('dashboard.settings.jobs.create.Dashboard') }}</a></li>
                <li>{{ __('dashboard.settings.jobs.create.Post a Job') }}</li>
            </ul>
        </nav>
    </div>

    @if ($errors->any())
        <div class="notification error closeable">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
            <a class="close"></a>
        </div>
    @endif

    <!-- Row -->
    <div class="row">

        <!-- Dashboard Box -->
        <div class="col-xl-12">
            <div class="dashboard-box margin-top-0">

                <!-- Headline -->
                <div class="headline">
                    <h3><i class="icon-feather-folder-plus"></i> {{ __('dashboard.settings.jobs.create.Job Submission Form') }}</h3>
                </div>

                <div class="content with-padding padding-bottom-10">
                    <div class="row">
                        <div class="col-xl-6">
                            <div class="submit-field">
                                <h5>{{ __('dashboard.settings.jobs.create.Job Title') }}</h5>
                                <input form="new-job" type="text" name="title" class="with-border"
                                       placeholder="{{ __('dashboard.settings.jobs.create.Job Title') }}">
                            </div>
                        </div>

                        <div class="col-xl-6">
                            <div class="submit-field">
                                <h5>@lang('dashboard.settings.jobs.create.Salary')</h5>
                                <div class="row">
                                    <div class="col-xl-6">
                                        <div class="input-with-icon">
                                            <input form="new-job" class="with-border" name="salary_min" type="text" placeholder="Min">
                                            <i class="currency">DZD</i>
                                        </div>
                                    </div>
                                    <div class="col-xl-6">
                                        <div class="input-with-icon">
                                            <input form="new-job" class="with-border" name="salary_max" type="text" placeholder="Max">
                                            <i class="currency">DZD</i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-xl-6">
                            <div class="submit-field">
                                <h5>{{ __('dashboard.settings.jobs.create.Job Type') }}</h5>
                                <select name="type" class="selectpicker with-border" data-size="7"
                                        form="new-job"
                                        title="Type du poste">
                                    <option value="Full Time">{{ __('app.types.Full Time') }}</option>
                                    <option value="Freelance">{{ __('app.types.Freelance') }}</option>
                                    <option value="Part Time">{{ __('app.types.Part Time') }}</option>
                                    <option value="Internship">{{ __('app.types.Internship') }}</option>
                                    <option value="Temporary">{{ __('app.types.Temporary') }}</option>
                                </select>
                            </div>
                        </div>

                        <div class="col-xl-6">
                            <div class="submit-field">
                                <h5>{{ __('dashboard.settings.jobs.edit.Job Category') }}</h5>
                                <select name="category" class="selectpicker with-border" data-size="7"
                                        form="new-job"
                                        title="sélectionner le domaine">
                                    <option value="Agriculture, alimentation et ressources naturelles">
                                        {{ __('app.categories.Agriculture, Food and Natural Resources') }}
                                    </option>
                                    <option value="Architecture et construction">
                                        {{ __('app.categories.Architecture and Construction') }}
                                    </option>
                                    <option value="Arts, technologie audio / vidéo et communications">
                                        {{ __('app.categories.Arts, Audio/Video Technology and Communications') }}
                                    </option>
                                    <option value="Gestion et administration des affaires">
                                        {{ __('app.categories.Business Management and Administration') }}
                                    </option>
                                    <option value="Éducation et formation">
                                        {{ __('app.categories.Education and Training') }}
                                    </option>
                                    <option value="La finance">
                                        {{ __('app.categories.Finance') }}
                                    </option>
                                    <option value="Gouvernement et administration publique">
                                        {{ __('app.categories.Government and Public Administration') }}
                                    </option>
                                    <option value="Sciences de la santé">
                                        {{ __('app.categories.Health Science') }}
                                    </option>
                                    <option value="Hospitalité et Tourisme">
                                        {{ __('app.categories.Hospitality and Tourism') }}
                                    </option>
                                    <option value="Services humains">
                                        {{ __('app.categories.Human Services') }}
                                    </option>
                                    <option value="Informatique">
                                        {{ __('app.categories.Information Technology') }}
                                    </option>
                                    <option value="Droit, sécurité publique, correction et sécurité">
                                        {{ __('app.categories.Law, Public Safety, Corrections and Security') }}
                                    </option>
                                    <option value="Fabrication">
                                        {{ __('app.categories.Manufacturing') }}
                                    </option>
                                    <option value="Marketing, ventes et service">
                                        {{ __('app.categories.Marketing, Sales and Service') }}
                                    </option>
                                    <option value="Science, technologie, ingénierie et mathématiques">
                                        {{ __('app.categories.Science, Technology, Engineering and Mathematics') }}
                                    </option>
                                    <option value="Transport, distribution et logistique">
                                        {{ __('app.categories.Transportation, Distribution & Logistics') }}
                                    </option>
                                </select>
                            </div>
                        </div>

                        <tags-editor class="col-xl-12" form-id="new-job" title="Compétences" optional info="Maximum of 10 tags"></tags-editor>

                        <text-editor class="col-xl-12" form-id="new-job" name="description"
                                     title="{{ __('dashboard.settings.jobs.create.Job Description') }}"></text-editor>

                        <div class="col-xl-12">
                            <attachments
                                optional
                                info="You need to save First"
                                upload-route="{{ route('dashboard.jobs.attachments.temp') }}"
                                remove-route="{{ route('dashboard.attachments.remove', '_uuid_') }}"
                                :attachments="{{ Auth::user()->getMedia('tempJobsAttachments')->toJson() }}"></attachments>
                        </div>

                        <locations
                            class="col-xl-12"
                            form-id="new-job"
                            location="{{ Auth::user()->location ?? '' }}"
                            :lat="{{ Auth::user()->lat ?? '36' }}"
                            :lng="{{ Auth::user()->lng ?? '2' }}"
                            :map_zoom="{{ Auth::user()->map_zoom ?? '6' }}"></locations>
                    </div>
                </div>
            </div>
        </div>
        <form method="POST" action="{{ route('dashboard.jobs.store') }}" id="new-job">
            @csrf

            <div class="col-xl-12">
                <button type="submit" class="button ripple-effect big margin-top-30"><i class="icon-feather-plus"></i>
                    {{ __('dashboard.settings.jobs.create.Save') }}
                </button>
            </div>
        </form>

    </div>
    <!-- Row / End -->
@endsection

@section('before-js')
    <script src="https://maps.googleapis.com/maps/api/js?key={{ config('google-maps.key') }}&libraries=places"></script>
@endsection

resources/views/dashboard/jobs/index.blade.php
@extends('layouts.dashboard')

@section('content')
    <!-- Dashboard Headline -->
    <div class="dashboard-headline">
        <h3>{{ __('dashboard.sidebar.Manage Jobs') }}</h3>

        <!-- Breadcrumbs -->
        <nav id="breadcrumbs" class="dark">
            <ul>
                <li><a href="{{ route('dashboard.home') }}">{{ __('dashboard.settings.jobs.index.Dashboard') }}</a></li>
                <li>{{ __('dashboard.settings.jobs.index.Manage Jobs') }}</li>
            </ul>
        </nav>
    </div>

    <!-- Row -->
    <div class="row">

        <!-- Dashboard Box -->
        <div class="col-xl-12">
            <div class="dashboard-box margin-top-0">

                <!-- Headline -->
                <div class="headline">
                    <h3>
                        <i class="icon-material-outline-business-center"></i> {{ __('dashboard.settings.jobs.index.My Job Listings') }}
                    </h3>
                </div>

                <div class="content">
                    <ul class="dashboard-box-list">
                        @foreach(Auth::user()->jobs as $job)
                            <li>
                                <!-- Job Listing -->
                                <div class="job-listing">
                                    <!-- Job Listing Details -->
                                    <div class="job-listing-details">
                                        <!-- Details -->
                                        <div class="job-listing-description">
                                            <h3 class="job-listing-title">
                                                <a href="#">{{ $job->title }}</a>
                                                {{--<span class="dashboard-status-button green">Pending Approval</span>--}}
                                            </h3>

                                            <!-- Job Listing Footer -->
                                            <div class="job-listing-footer">
                                                <ul>
                                                    <li>
                                                        <i class="icon-material-outline-assignment"></i>
                                                        {{ $job->type }}
                                                    </li>
                                                    <li>
                                                        <i class="icon-material-outline-business-center"></i>
                                                        {{ $job->category }}
                                                    </li>
                                                    <li>
                                                        <i class="icon-material-outline-date-range"></i>
                                                        {{ $job->created_at->format('Y/m/d') }}
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <!-- Buttons -->
                                <div class="buttons-to-right always-visible">
                                    <a href="{{ route('dashboard.jobs.candidates', $job->id) }}"
                                       class="button ripple-effect"><i
                                            class="icon-material-outline-supervisor-account"></i> {{ __('dashboard.settings.jobs.index.Manage Candidates') }}
                                        <span
                                            class="button-info">{{ $job->candidates->count() }}</span></a>
                                    <a href="{{ route('dashboard.jobs.edit', $job->id) }}"
                                       class="button gray ripple-effect ico"
                                       title="{{ __('dashboard.settings.jobs.index.Edit') }}"
                                       data-tippy-placement="top"><i class="icon-feather-edit"></i></a>
                                    <a href="#" class="button gray ripple-effect ico"
                                       onclick="event.preventDefault();
                                           document.getElementById('delete-form-{{ $job->id }}').submit();"
                                       title="{{ __('dashboard.settings.jobs.index.Remove') }}"
                                       data-tippy-placement="top">
                                        <i class="icon-feather-trash-2"></i></a>
                                    <form id="delete-form-{{ $job->id }}"
                                          action="{{ route('dashboard.jobs.destroy',$job->id) }}"
                                          method="POST"
                                          style="display: none;">
                                        @csrf
                                        @method('DELETE')
                                    </form>
                                </div>
                            </li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>

    </div>
    <!-- Row / End -->
@endsection