routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@welcome')->name('welcome');

Route::get('/how-it-works', function () {
    return view('how-it-works');
})->name('how-it-works');

Route::get('/contact', function () {
    return view('contact');
})->name('contact');

Auth::routes();


Route::get('companies', 'CompanyController@index')->name('companies');
Route::get('companies/{company}', 'CompanyController@show')->name('companies.show');
Route::get('/download/{uuid}', 'MediaController@download')->name('download');


Route::resource('jobs','FrontJobsController');
Route::resource('users', 'FrontUsersController');

Route::get('fr', function() {
    cookie()->forever('locale','fr');
    return redirect()->back()->cookie('locale', 'fr', 5256000);
});

Route::get('en', function() {
    return redirect()->back()->cookie('locale', 'en', 5256000);
});

Route::get('lang/{key}', function ($key) {
   return Lang::get('components.'.$key);
});


Route::middleware('auth')->prefix('dashboard')->name('dashboard.')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/settings', 'UserController@account')->name('settings');
    Route::get('/settings/password', 'UserController@password')->name('settings.password');
    Route::put('/settings', 'UserController@update')->name('settings.update');
    Route::put('/settings/password', 'UserController@updatePassword')->name('settings.password.update');
    Route::post('/settings/attachments', 'UserController@uploadAttachment')->name('settings.upload');
    Route::delete('/settings/attachments/{uuid}', 'UserController@removeAttachment')->name('attachments.remove');


    Route::resource('jobs','JobController')->middleware('type:employer');
    Route::post('jobs/attachments/temp','JobController@tempAttachments')->name('jobs.attachments.temp');
    Route::post('jobs/{id}/attachments/temp','JobController@addAttachments')->name('jobs.attachments.add');
    Route::delete('jobs/attachments/delete/{uuid}','JobController@removeAttachment')->name('jobs.attachments.delete');

    Route::get('jobs/{job}/candidates','JobController@candidates')->name('jobs.candidates');
    Route::get('jobs/{job}/candidates/{candidate}','JobController@showCandidates')->name('jobs.candidates.show');
    Route::delete('jobs/{job}/candidates/{candidate}','JobController@deleteCandidates')->name('jobs.candidates.destroy');

    Route::resource('candidates', 'CandidateController')->middleware('type:freelancer');

    Route::post('candidates/{id}/attachments/temp','CandidateController@addAttachments')->name('candidates.attachments.add');
    Route::delete('candidates/attachments/delete/{uuid}','CandidateController@removeAttachment')->name('candidates.attachments.delete');

    Route::resource('bookmarks', 'BookmarkController');
});

resources/views/dashboard/settings/account.blade.php
@extends('layouts.dashboard')

@section('content')
    <!-- Dashboard Headline -->
    <div class="dashboard-headline">
        <h3>{{ __('dashboard.settings.account.Update Account') }}</h3>

        <!-- Breadcrumbs -->
        <nav id="breadcrumbs" class="dark">
            <ul>
                <li><a href="{{ route('dashboard.home') }}">{{ __('dashboard.settings.account.Dashboard') }}</a></li>
                <li>{{ __('dashboard.settings.account.Settings') }}</li>
                <li>{{ __('dashboard.settings.account.Update Account') }}</li>
            </ul>
        </nav>
    </div>

    <!-- Row -->

    @if ($errors->any())
        <div class="notification error closeable">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
            <a class="close"></a>
        </div>
    @endif

    <div class="row">

        <!-- Dashboard Box -->

        <div class="col-xl-12">
            <form id="settings-update" action="{{ route('dashboard.settings.update') }}" method="post"
                  enctype="multipart/form-data">
                @method('PUT')
                @csrf
                <div class="dashboard-box margin-top-0">

                    <!-- Headline -->
                    <div class="headline">
                        <h3><i class="icon-material-outline-account-circle"></i> {{ __('dashboard.settings.account.form.My Account') }}</h3>
                    </div>

                    <div class="content with-padding padding-bottom-0">

                        <div class="row">

                            <div class="col-sm-auto d-flex align-items-center justify-content-center">
                                <div class="avatar-wrapper" data-tippy-placement="bottom" title="{{ __('dashboard.settings.account.form.Change Avatar') }}">
                                    <img class="profile-pic"
                                         src="{{ Auth::user()->image() ?? asset('images/user-avatar-placeholder.png') }}"
                                         alt="" />
                                    <div class="upload-button"></div>
                                    <input class="file-upload" name="image" type="file" accept="image/*" />
                                </div>
                            </div>

                            <div class="col">
                                <div class="row">

                                    <div class="col-xl-6">
                                        <div class="submit-field">
                                            <h5>{{ __('dashboard.settings.account.form.Full Name') }}</h5>
                                            <input type="text" name="name" class="with-border" required
                                                   placeholder="{{ __('dashboard.settings.account.form.Full Name') }}"
                                                   value="{{ Auth::user()->name }}">
                                        </div>
                                    </div>

                                    <div class="col-xl-6">
                                        <div class="submit-field">
                                            <h5>{{ __('dashboard.settings.account.form.Email') }}</h5>
                                            <input type="text" name="email" class="with-border" required
                                                   placeholder="{{ __('dashboard.settings.account.form.Email') }}"
                                                   value="{{ Auth::user()->email }}">
                                        </div>
                                    </div>

                                    <div class="col-xl-6">
                                        <!-- Account Type -->
                                        <div class="submit-field">
                                            <h5>{{ __('dashboard.settings.account.form.Account Type') }}</h5>
                                            @if(Auth::user()->employer)
                                                <div class="account-type">
                                                    <div class="d-flex">
                                                        <button disabled
                                                                class="button ripple-effect green full-width margin-right-15">
                                                            <i class="icon-material-outline-business-center"></i>
                                                            {{ __('dashboard.settings.account.form.Employer') }}
                                                        </button>
                                                        <a href="{{ route('companies.show', Auth::id()) }}"
                                                           target="_blank"
                                                           class="button ripple-effect full-width">
                                                            {{ __('dashboard.settings.account.form.Preview') }} <i class="icon-material-outline-launch"></i>
                                                        </a>
                                                    </div>
                                                </div>
                                            @else
                                                <div class="account-type">
                                                    <div class="d-flex">
                                                        <button disabled
                                                                class="button ripple-effect green full-width margin-right-15">
                                                            <i class="icon-material-outline-account-circle"></i>
                                                            {{ __('dashboard.settings.account.form.Freelancer') }}
                                                        </button>
                                                        <a href="{{ route('companies.show', Auth::id()) }}"
                                                           target="_blank"
                                                           class="button ripple-effect full-width">
                                                            {{ __('dashboard.settings.account.form.Preview') }} <i class="icon-material-outline-launch"></i>
                                                        </a>
                                                    </div>
                                                </div>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="col-xl-6">
                                        <div class="submit-field">
                                            <h5>{{ __('dashboard.settings.account.form.Phone') }}</h5>
                                            <input type="tel" name="phone" class="with-border"
                                                   placeholder="+213 ..."
                                                   value="{{ Auth::user()->phone }}">
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </form>
        </div>

        <!-- Dashboard Box -->
        <div class="col-xl-12">
            <div class="dashboard-box">

                <!-- Headline -->
                <div class="headline">
                    <h3><i class="icon-material-outline-description"></i> {{ __('dashboard.settings.account.form.Details') }}</h3>
                </div>

                <div class="content">
                    <ul class="fields-ul">
                        @if(Auth::user()->freelancer)
                            <li>
                                <div class="row">
                                    <tags-editor
                                        class="col-xl-6"
                                        title="{{ __('dashboard.settings.account.form.Skills') }}"
                                        info="{{ __('dashboard.settings.account.form.Add up to 10 skills') }}"
                                        form-id="settings-update"
                                        tags="{{ Auth::user()->skills ? json_encode(Auth::user()->skills) : '' }}"
                                        name="skills"
                                    ></tags-editor>

                                    <div class="col-xl-6">
                                        <attachments
                                            upload-route="{{ route('dashboard.settings.upload') }}"
                                            remove-route="{{ route('dashboard.attachments.remove', '_uuid_') }}"
                                            :attachments="{{ Auth::user()->getMedia('attachments')->toJson() }}"
                                        ></attachments>
                                    </div>
                                </div>
                            </li>
                        @else
                            <input type="hidden" name="skills" form="settings-update" />
                        @endif
                        <li>
                            <div class="row">
                                <div class="col-xl-12">
                                    <div class="submit-field">
                                        <h5>{{ __('dashboard.settings.account.form.Title') }}</h5>
                                        <input type="text" name="title" form="settings-update"
                                               value="{{ Auth::user()->title }}"
                                               class="with-border" placeholder="{{ __('dashboard.settings.account.form.Job Title') }}">
                                    </div>
                                </div>

                                <text-editor class="col-xl-12"
                                             name="description"
                                             title="{{ __('dashboard.settings.account.form.Introduce Yourself') }}"
                                             form-id="settings-update"
                                             content="{{ Auth::user()->description }}"></text-editor>

                                <locations class="col-xl-12"
                                           form-id="settings-update"
                                           :lat="{{ Auth::user()->lat ?? 34.8471273 }}"
                                           :lng="{{ Auth::user()->lng ?? 1.5450766 }}"
                                           :map_zoom="{{ Auth::user()->map_zoom ?? 6 }}"
                                           location="{{ Auth::user()->location ?? '' }}"
                                ></locations>

                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Button -->
        <div class="col-xl-12">
            <input type="hidden" form="settings-update" name="apply_to_job" id="applyToJob">
            <button type="submit" form="settings-update" class="button ripple-effect big margin-top-30">
                {{ __('dashboard.settings.account.form.Save Changes') }}
            </button>
        </div>

    </div>
    <!-- Row / End -->
@endsection

@section('before-js')
    <script
        src="https://maps.googleapis.com/maps/api/js?key={{ config('google-maps.key') }}&libraries=places"></script>
@endsection

@section('after-js')
    <script>
    jobid = localStorage.getItem('applyToJob')
    if (jobid) {
        $('#applyToJob').val(jobid)
    }
    </script>
@endsection

resources/views/dashboard/settings/password.blade.php
@extends('layouts.dashboard')

@section('content')
    <!-- Dashboard Headline -->
    <div class="dashboard-headline">
        <h3>{{ __('dashboard.settings.password.Update password') }}</h3>

        <!-- Breadcrumbs -->
        <nav id="breadcrumbs" class="dark">
            <ul>
                <li><a href="{{ route('dashboard.home') }}">{{ __('dashboard.settings.password.Dashboard') }}</a></li>
                <li><a href="{{ route('dashboard.settings') }}">{{ __('dashboard.settings.password.Settings') }}</a></li>
                <li>{{ __('dashboard.settings.password.Update password') }}</li>
            </ul>
        </nav>
    </div>

    <!-- Row -->

    @if ($errors->any())
        <div class="notification error closeable">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
            <a class="close"></a>
        </div>
    @endif

    <div class="row">

        <!-- Dashboard Box -->
        <div class="col-xl-12">
            <div id="test1" class="dashboard-box">

                <!-- Headline -->
                <div class="headline">
                    <h3><i class="icon-material-outline-lock"></i> {{ __('dashboard.settings.password.form.Password & Security') }}</h3>
                </div>

                <form id="settings-password" action="{{ route('dashboard.settings.password.update') }}" method="post">
                    @method('PUT')
                    @csrf

                    <div class="content with-padding">
                        <div class="row">
                            <div class="col-xl-12">
                                <div class="submit-field">
                                    <h5>{{ __('dashboard.settings.password.form.Current Password') }}</h5>
                                    <input type="password" name="password" class="with-border">
                                </div>
                            </div>

                            <div class="col-xl-12">
                                <div class="submit-field">
                                    <h5>{{ __('dashboard.settings.password.form.New Password') }}</h5>
                                    <input type="password" name="new_password" class="with-border">
                                </div>
                            </div>

                            <div class="col-xl-12">
                                <div class="submit-field">
                                    <h5>{{ __('dashboard.settings.password.form.Repeat New Password') }}</h5>
                                    <input type="password" name="new_password_confirmation" class="with-border">
                                </div>
                            </div>

                        </div>
                    </div>
                </form>
            </div>
        </div>

        <!-- Button -->
        <div class="col-xl-12">
            <button type="submit" form="settings-password" class="button ripple-effect big margin-top-30">
                {{ __('dashboard.settings.password.form.Save Changes') }}
            </button>
        </div>

    </div>
    <!-- Row / End -->
@endsection