routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@welcome')->name('welcome');

Route::get('/how-it-works', function () {
    return view('how-it-works');
})->name('how-it-works');

Route::get('/contact', function () {
    return view('contact');
})->name('contact');

Auth::routes();


Route::get('companies', 'CompanyController@index')->name('companies');
Route::get('companies/{company}', 'CompanyController@show')->name('companies.show');
Route::get('/download/{uuid}', 'MediaController@download')->name('download');


Route::resource('jobs','FrontJobsController');
Route::resource('users', 'FrontUsersController');

Route::get('fr', function() {
    cookie()->forever('locale','fr');
    return redirect()->back()->cookie('locale', 'fr', 5256000);
});

Route::get('en', function() {
    return redirect()->back()->cookie('locale', 'en', 5256000);
});

Route::get('lang/{key}', function ($key) {
   return Lang::get('components.'.$key);
});


Route::middleware('auth')->prefix('dashboard')->name('dashboard.')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/settings', 'UserController@account')->name('settings');
    Route::get('/settings/password', 'UserController@password')->name('settings.password');
    Route::put('/settings', 'UserController@update')->name('settings.update');
    Route::put('/settings/password', 'UserController@updatePassword')->name('settings.password.update');
    Route::post('/settings/attachments', 'UserController@uploadAttachment')->name('settings.upload');
    Route::delete('/settings/attachments/{uuid}', 'UserController@removeAttachment')->name('attachments.remove');


    Route::resource('jobs','JobController')->middleware('type:employer');
    Route::post('jobs/attachments/temp','JobController@tempAttachments')->name('jobs.attachments.temp');
    Route::post('jobs/{id}/attachments/temp','JobController@addAttachments')->name('jobs.attachments.add');
    Route::delete('jobs/attachments/delete/{uuid}','JobController@removeAttachment')->name('jobs.attachments.delete');

    Route::get('jobs/{job}/candidates','JobController@candidates')->name('jobs.candidates');
    Route::get('jobs/{job}/candidates/{candidate}','JobController@showCandidates')->name('jobs.candidates.show');
    Route::delete('jobs/{job}/candidates/{candidate}','JobController@deleteCandidates')->name('jobs.candidates.destroy');

    Route::resource('candidates', 'CandidateController')->middleware('type:freelancer');

    Route::post('candidates/{id}/attachments/temp','CandidateController@addAttachments')->name('candidates.attachments.add');
    Route::delete('candidates/attachments/delete/{uuid}','CandidateController@removeAttachment')->name('candidates.attachments.delete');

    Route::resource('bookmarks', 'BookmarkController');
});

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class CompanyController extends Controller
{
    public function index()
    {
        $query = User::where('employer', 1)->limit(12);

        if (request()->has('letter'))
            $query->where('name', 'like', request()->get('letter') . '%');


        $companies = $query->get();
        foreach ($companies as $company) {
            $company->logo = $company->image();
            $company->url = route('companies.show', $company);
        }

        return view('companies.index', compact('companies', ));
    }

    public function show(User $company)
    {
        if ($company->employer) {
            $jobs = $company->jobs()->latest()->paginate(3, ['*'], 'jobs');
            return view('companies.show', compact('company', 'jobs'));
        }
        else {
            return abort(404);
        }
    }
}

resources/views/companies/index.blade.php
@extends('layouts.app')

@section('content')

    <!-- Titlebar
    ================================================== -->
    <div id="titlebar" class="gradient">
        <div class="container">
            <div class="row">
                <div class="col-md-12">

                    <h2>{{ __('app.footer.Browse Companies') }}</h2>

                    <!-- Breadcrumbs -->
                    <nav id="breadcrumbs" class="dark">
                        <ul>
                            <li><a href="{{ route('welcome') }}">{{ __('front.companies.index.Home') }}</a></li>
                            <li>{{ __('front.companies.index.Companies') }}</li>
                        </ul>
                    </nav>

                </div>
            </div>
        </div>
    </div>

    <!-- Page Content
    ================================================== -->

    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <company-letters-filter />
            </div>
            <div class="col-xl-12">
                @if(count($companies))
                    <companies-list :companies="{{ $companies->toJson() }}"></companies-list>
                @else
                    <div class="companies-list d-flex align-items-center justify-content-center flex-column">
                        <div style="height: 287px">
                            <img src="{{ asset('images/noresults.png') }}" alt="">
                            <h3>{{ __('front.companies.index.Nothing found') }}</h3>
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/companies/show.blade.php
@extends('layouts.app')

@section('content')
    <!-- Titlebar
================================================== -->
    <div class="single-page-header" data-background-image="{{ asset('images/single-company.jpg') }}">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="single-page-header-inner">
                        <div class="left-side">
                            <div class="header-image"><img src="{{ $company->image() }}" alt=""></div>
                            <div class="header-details">
                                <h3>{{ $company->name }}<span>{{ $company->title }}</span></h3>
                                <p>{{ $company->location }}</p>
                                <ul>
                                    {{--<li>
                                        <div class="star-rating" data-rating="4.9"></div>
                                    </li>--}}
                                    {{--<li>
                                        <div class="verified-badge-with-title">Verified</div>
                                    </li>--}}
                                </ul>

                            </div>
                        </div>
                        <div class="right-side">
                            <!-- Breadcrumbs -->
                            <nav id="breadcrumbs" class="white">
                                <ul>
                                    <li><a href="{{ route('welcome') }}">{{ __('front.companies.index.Home') }}</a></li>
                                    <li><a href="{{ route('companies') }}">{{ __('front.companies.index.Companies') }}</a></li>
                                    <li>{{ $company->name }}</li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Page Content
    ================================================== -->
    <div class="container">
        <div class="row">

            <!-- Content -->
            <div class="col-xl-8 col-lg-8 content-right-offset">

                <div class="single-page-section">
                    <h3 class="margin-bottom-25">{{ __('front.companies.show.About Company') }}</h3>
                    {!! html_entity_decode($company->description) !!}
                </div>

                <!-- Boxed List -->
                <div class="boxed-list margin-bottom-60">
                    <div class="boxed-list-headline">
                        <h3><i class="icon-material-outline-business-center"></i> {{ __('Open Positions') }}</h3>
                    </div>

                    <div class="listings-container compact-list-layout">

                        <!-- Job Listing -->
                        @foreach($jobs as $job)
                            <a href="{{ route('jobs.show', $job->id) }}" class="job-listing">

                                <!-- Job Listing Details -->
                                <div class="job-listing-details">

                                    <!-- Details -->
                                    <div class="job-listing-description">
                                        <h3 class="job-listing-title">{{ $job->title }}</h3>

                                        <!-- Job Listing Footer -->
                                        <div class="job-listing-footer">
                                            <ul>
                                                <li><i class="icon-material-outline-location-on"></i>{{ $job->location }}</li>
                                                <li><i class="icon-material-outline-business-center"></i>{{ $job->type }}</li>
                                                <li>
                                                    <i class="icon-material-outline-access-time"></i>
                                                    {{ $job->created_at->diffForHumans() }}
                                                </li>
                                            </ul>
                                        </div>
                                    </div>

                                </div>

                                <!-- Bookmark -->
                                @auth()
                                    <book-mark id="{{ $job->bookmark() ? $job->bookmark()->id : '' }}"
                                               model-id="{{ $job->id }}"
                                               model-type="job"
                                               add-route="{{ route('dashboard.bookmarks.store') }}"
                                               remove-route="{{ route('dashboard.bookmarks.destroy','_id_' ) }}"
                                    ></book-mark>
                                @endauth
                            </a>
                        @endforeach
                    </div>

                    {{ $jobs->links('layouts.pagination.dafault') }}
                </div>
                <!-- Boxed List / End -->

                {{--<!-- Boxed List -->
                <div class="boxed-list margin-bottom-60">
                    <div class="boxed-list-headline">
                        <h3><i class="icon-material-outline-thumb-up"></i> Reviews</h3>
                    </div>
                    <ul class="boxed-list-ul">
                        <li>
                            <div class="boxed-list-item">
                                <!-- Content -->
                                <div class="item-content">
                                    <h4>Doing things the right way <span>Anonymous Employee</span></h4>
                                    <div class="item-details margin-top-10">
                                        <div class="star-rating" data-rating="5.0"></div>
                                        <div class="detail-item"><i class="icon-material-outline-date-range"></i> August
                                            2018
                                        </div>
                                    </div>
                                    <div class="item-description">
                                        <p>Great company and especially ideal for the career-minded individual. The
                                            company is large enough to offer a variety of jobs in all kinds of
                                            interesting locations. Even if you never change roles, your job changes and
                                            evolves as the company grows, keeping things fresh.</p>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="boxed-list-item">
                                <!-- Content -->
                                <div class="item-content">
                                    <h4>Outstanding Work Environment <span>Anonymous Employee</span></h4>
                                    <div class="item-details margin-top-10">
                                        <div class="star-rating" data-rating="5.0"></div>
                                        <div class="detail-item"><i class="icon-material-outline-date-range"></i> May
                                            2018
                                        </div>
                                    </div>
                                    <div class="item-description">
                                        <p>They do business with integrity and rational thinking. Overall, it's an
                                            excellent place to work, with products that are winning in the
                                            marketplace.</p>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>

                    <div class="centered-button margin-top-35">
                        <a href="#small-dialog" class="popup-with-zoom-anim button button-sliding-icon">Leave a Review
                            <i class="icon-material-outline-arrow-right-alt"></i></a>
                    </div>

                </div>
                <!-- Boxed List / End -->--}}

            </div>

            <!-- Sidebar -->
            <div class="col-xl-4 col-lg-4">
                <div class="sidebar-container">

                    <!-- Location -->
                    <div class="sidebar-widget">
                        <h3>{{ __('front.companies.show.Location') }}</h3>
                        <div id="single-job-map-container">
                            <div id="singleListingMap" data-latitude="{{ $company->lat }}"
                                 data-longitude="{{ $company->lng }}"
                                 data-map-icon="im im-icon-Hamburger"></div>
                            <a href="#" id="streetView">Street View</a>
                        </div>
                    </div>

                    <!-- Widget -->
                    <!--
                    <div class="sidebar-widget">
                        <h3>{{ __('front.companies.show.Social Profiles') }}</h3>
                        <div class="freelancer-socials margin-top-25">
                            <ul>
                                <li><a href="#" title="Dribbble" data-tippy-placement="top"><i
                                            class="icon-brand-dribbble"></i></a></li>
                                <li><a href="#" title="Twitter" data-tippy-placement="top"><i
                                            class="icon-brand-twitter"></i></a></li>
                                <li><a href="#" title="Behance" data-tippy-placement="top"><i
                                            class="icon-brand-behance"></i></a></li>
                                <li><a href="#" title="GitHub" data-tippy-placement="top"><i
                                            class="icon-brand-github"></i></a></li>

                            </ul>
                        </div>
                    </div>
                    -->

                    <!-- Sidebar Widget -->
                    <div class="sidebar-widget">
                        <h3>{{ __('front.companies.show.Bookmark or Share') }}</h3>

                        <!-- Bookmark Button -->
                        <book-mark
                            class="margin-bottom-25"
                            show-button
                            id="{{ $company->companyBookmark() ? $company->companyBookmark()->id : '' }}"
                            model-id="{{ $company->id }}"
                            model-type="company"
                            add-route="{{ route('dashboard.bookmarks.store') }}"
                            remove-route="{{ route('dashboard.bookmarks.destroy','_id_' ) }}"
                        ></book-mark>

                        <!-- Copy URL -->
                        <div class="copy-url">
                            <input id="copy-url" type="text" value="" class="with-border">
                            <button class="copy-url-button ripple-effect" data-clipboard-target="#copy-url"
                                    title="Copy to Clipboard" data-tippy-placement="top"><i
                                    class="icon-material-outline-file-copy"></i></button>
                        </div>

                        <!-- Share Buttons -->
                        <!--
                        <div class="share-buttons margin-top-25">
                            <div class="share-buttons-trigger"><i class="icon-feather-share-2"></i></div>
                            <div class="share-buttons-content">
                                <span>@lang('front.companies.show.Interesting? Share It!')</span>
                                <ul class="share-buttons-icons">
                                    <li><a href="#" data-button-color="#3b5998" title="Share on Facebook"
                                           data-tippy-placement="top"><i class="icon-brand-facebook-f"></i></a></li>
                                    <li><a href="#" data-button-color="#1da1f2" title="Share on Twitter"
                                           data-tippy-placement="top"><i class="icon-brand-twitter"></i></a></li>
                                    <li><a href="#" data-button-color="#dd4b39" title="Share on Google Plus"
                                           data-tippy-placement="top"><i class="icon-brand-google-plus-g"></i></a></li>
                                    <li><a href="#" data-button-color="#0077b5" title="Share on LinkedIn"
                                           data-tippy-placement="top"><i class="icon-brand-linkedin-in"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        -->
                    </div>

                </div>
            </div>

        </div>
    </div>
@endsection

@section('after-js')
    <!-- Snackbar // documentation: https://www.polonel.com/snackbar/ -->
    <script>

    // Snackbar for copy to clipboard button
    $('.copy-url-button').click(function () {
        Snackbar.show({
            text: '{{ __('front.companies.show.Copied to clipboard!') }}',
        })
    })
    </script>

    <!-- Google API & Maps -->
    <script
        src="https://maps.googleapis.com/maps/api/js?key={{ config('google-maps.key') }}&libraries=places"></script>
    <script src="{{ asset('js/maps/infobox.min.js') }}"></script>
    <script src="{{ asset('js/markerclusterer.js') }}"></script>
    <script src="{{ asset('js/maps.js') }}"></script>
@endsection