routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@welcome')->name('welcome');

Route::get('/how-it-works', function () {
    return view('how-it-works');
})->name('how-it-works');

Route::get('/contact', function () {
    return view('contact');
})->name('contact');

Auth::routes();


Route::get('companies', 'CompanyController@index')->name('companies');
Route::get('companies/{company}', 'CompanyController@show')->name('companies.show');
Route::get('/download/{uuid}', 'MediaController@download')->name('download');


Route::resource('jobs','FrontJobsController');
Route::resource('users', 'FrontUsersController');

Route::get('fr', function() {
    cookie()->forever('locale','fr');
    return redirect()->back()->cookie('locale', 'fr', 5256000);
});

Route::get('en', function() {
    return redirect()->back()->cookie('locale', 'en', 5256000);
});

Route::get('lang/{key}', function ($key) {
   return Lang::get('components.'.$key);
});


Route::middleware('auth')->prefix('dashboard')->name('dashboard.')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/settings', 'UserController@account')->name('settings');
    Route::get('/settings/password', 'UserController@password')->name('settings.password');
    Route::put('/settings', 'UserController@update')->name('settings.update');
    Route::put('/settings/password', 'UserController@updatePassword')->name('settings.password.update');
    Route::post('/settings/attachments', 'UserController@uploadAttachment')->name('settings.upload');
    Route::delete('/settings/attachments/{uuid}', 'UserController@removeAttachment')->name('attachments.remove');


    Route::resource('jobs','JobController')->middleware('type:employer');
    Route::post('jobs/attachments/temp','JobController@tempAttachments')->name('jobs.attachments.temp');
    Route::post('jobs/{id}/attachments/temp','JobController@addAttachments')->name('jobs.attachments.add');
    Route::delete('jobs/attachments/delete/{uuid}','JobController@removeAttachment')->name('jobs.attachments.delete');

    Route::get('jobs/{job}/candidates','JobController@candidates')->name('jobs.candidates');
    Route::get('jobs/{job}/candidates/{candidate}','JobController@showCandidates')->name('jobs.candidates.show');
    Route::delete('jobs/{job}/candidates/{candidate}','JobController@deleteCandidates')->name('jobs.candidates.destroy');

    Route::resource('candidates', 'CandidateController')->middleware('type:freelancer');

    Route::post('candidates/{id}/attachments/temp','CandidateController@addAttachments')->name('candidates.attachments.add');
    Route::delete('candidates/attachments/delete/{uuid}','CandidateController@removeAttachment')->name('candidates.attachments.delete');

    Route::resource('bookmarks', 'BookmarkController');
});

app/Job.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

/**
 * App\Job
 *
 * @property int $id
 * @property string $title
 * @property string $type
 * @property string $category
 * @property string|null $location
 * @property float|null $lng
 * @property float|null $lat
 * @property int|null $map_zoom
 * @property int|null $salary_min
 * @property int|null $salary_max
 * @property array|null $tags
 * @property string $description
 * @property int $user_id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Bookmark[] $bookmarks
 * @property-read int|null $bookmarks_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Candidate[] $candidates
 * @property-read int|null $candidates_count
 * @property-read \App\User $company
 * @property-read \Spatie\MediaLibrary\MediaCollections\Models\Collections\MediaCollection|\Spatie\MediaLibrary\MediaCollections\Models\Media[] $media
 * @property-read int|null $media_count
 * @method static \Illuminate\Database\Eloquent\Builder|Job newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Job newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Job query()
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereCategory($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereLat($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereLng($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereLocation($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereMapZoom($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereSalaryMax($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereSalaryMin($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereTags($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereType($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Job whereUserId($value)
 * @mixin \Eloquent
 */
class Job extends Model implements HasMedia
{

    use InteractsWithMedia;

    protected $fillable = [
        'title',
        'type',
        'category',
        'location',
        'lat',
        'lng',
        'map_zoom',
        'salary_min',
        'salary_max',
        'tags',
        'description',
        'user_id',
    ];

    protected $casts = [
        'tags' => 'array',
        'lat' => 'double',
        'lng' => 'double',
        'map_zoom' => 'integer'
    ];

    public function company(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function similarJobs()
    {
        return Job::where('id', '<>', $this->id)
            ->where('category', $this->category)
            ->limit(2)
            ->get();
    }

    public function candidates(): HasMany
    {
        return $this->hasMany(Candidate::class);
    }

    public function bookmarks(): HasMany
    {
        return $this->hasMany(Bookmark::class);
    }

    public function bookmark()
    {
        return $this->bookmarks()->where('user_id', \Auth::id())
            ->limit(1)->first();
    }

    public static function customSearchQuery(array $params)
    {
        $query = Job::getQuery();

        if (key_exists('lat', $params) and
            key_exists('lng', $params) and
            key_exists('distance', $params) and
            key_exists('location', $params) and
            $params['lat'] and
            $params['lng'] and
            $params['distance'] and
            $params['location']
        ) {
            $lat = $params['lat'];
            $lng = $params['lng'];
            $distance = $params['distance'];

            $query = $query->whereRaw('lat BETWEEN ( ? - ( ? * 0.0117)) AND ( ? + ( ? * 0.0117))', [$lat, $distance, $lat, $distance]);
            $query = $query->whereRaw('lng BETWEEN ( ? - ( ? * 0.0117)) AND ( ? + ( ? * 0.0117))', [$lng, $distance, $lng, $distance]);
        }

        if (key_exists('keywords', $params) and $params['keywords']) {
            $keywords = explode(',', $params['keywords']);
            if (count($keywords)) {
                $query = $query->whereRaw('MATCH (title ,description) AGAINST (?)', $keywords);
            }
        }

        if (key_exists('salary', $params)) {
            $salary = explode(',', $params['salary']);
            $query = $query
                ->where('salary_min', '<=', $salary[1])
                ->where('salary_max', '>=', $salary[0]);
        }

        if (key_exists('categories', $params)) {
            $categoriesSearch = $params['categories'];
            if (count($categoriesSearch)) {
                $query = $query->whereIn('category', $categoriesSearch);
            }
        }

        if (key_exists('types', $params)) {
            $typesSearch = $params['types'];
            if (count($typesSearch)) {
                $query = $query->whereIn('type', $typesSearch);
            }
        }

        return $query;
    }
}

app/Http/Controllers/JobController.php
<?php

namespace App\Http\Controllers;

use App\Candidate;
use App\Job;
use App\User;
use Auth;
use Illuminate\Http\Request;
use Spatie\MediaLibrary\MediaCollections\Exceptions\FileDoesNotExist;
use Spatie\MediaLibrary\MediaCollections\Exceptions\FileIsTooBig;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class JobController extends Controller
{
    public function index()
    {
        $jobs = Auth::user()->jobs;
        return view('dashboard.jobs.index', compact('jobs'));
    }

    public function create()
    {
        return view('dashboard.jobs.create');
    }


    public function store(Request $request)
    {
        $validated_data = $request->validate([
            'title' => 'required|string',
            'type' => 'required|string',
            'category' => 'required|string',
            'location' => 'nullable|string',
            'lat' => 'nullable|string',
            'lng' => 'nullable|string',
            'map_zoom' => 'nullable|string',
            'salary_min' => 'nullable|string',
            'salary_max' => 'nullable|string',
            'tags' => 'nullable|string',
            'description' => 'required|string',
        ]);

        $user = User::find(Auth::id());

        $validated_data["tags"] = explode(',', $validated_data["tags"]);

        $job = Auth::user()->jobs()->create($validated_data);

        foreach ($user->getMedia('tempJobsAttachments') as $media) {
            $media->copy($job, 'attachments');
            $media->delete();
        }

        return redirect()->route('dashboard.jobs.edit', $job->id)->with('message', 'job created successfully');
    }


    public function show(Job $job)
    {
        $job->getMedia();
        return $job;
    }


    public function edit(Job $job)
    {
        return view('dashboard.jobs.edit', compact('job'));
    }


    public function update(Request $request, Job $job)
    {
        $validated_data = $request->validate([
            'title' => 'required|string',
            'type' => 'required|string',
            'category' => 'required|string',
            'location' => 'nullable|string',
            'lat' => 'nullable|string',
            'lng' => 'nullable|string',
            'map_zoom' => 'nullable|string',
            'salary_min' => 'nullable|string',
            'salary_max' => 'nullable|string',
            'tags' => 'nullable|string',
            'description' => 'required|string',
        ]);

        $validated_data["tags"] = explode(',', $validated_data["tags"]);

        $job->update($validated_data);

        return redirect()->route('dashboard.jobs.edit', $job->id)
            ->with('message', 'job updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Job $job
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Job $job)
    {
        try {
            Auth::user()->jobs()->findOrFail($job->id)->delete();
            return redirect()->back()->with('message', 'job deleted');
        } catch (\Exception $e) {
            throw $e;
        }
    }

    public function tempAttachments(Request $request)
    {
        $user = User::find(Auth::id());
        try {
            $file = $user->addMediaFromRequest('file')
                ->toMediaCollection('tempJobsAttachments');
            return response()->json($file);
        } catch (FileDoesNotExist $e) {
        } catch (FileIsTooBig $e) {
        }
        return null;
    }

    public function addAttachments($id, Request $request)
    {
        $user = User::find(Auth::id());
        $job = $user->jobs->find($id);
        try {
            $file = $job->addMediaFromRequest('file')
                ->toMediaCollection('attachments');
            return response()->json($file);
        } catch (FileDoesNotExist $e) {
        } catch (FileIsTooBig $e) {
        }
        return null;
    }

    public function removeAttachment($uuid)
    {
        $media = Media::findByUuid($uuid);
        $user = User::find(Auth::id());

        try {
            if ($user->jobs->find($media->getAttribute('model_id')))
                if ($media->delete())
                    return response()->noContent();
            return 'nop!';
        } catch (\Exception $e) {
        }

        return null;
    }

    public function candidates(Job $job) {
        return view('dashboard.jobs.candidates.index', compact('job'));
    }

    public function showCandidates(Job $job, Candidate $candidate) {

        $user = $candidate->user;
        return view('dashboard.jobs.candidates.show', compact('job','candidate', 'user'));
    }

    public function deleteCandidates(Job $job, Candidate $candidate) {
        Auth::user()->jobs()->findOrFail($job->id);
        $job->candidates()->findOrFail($candidate->id);
        try {
            $candidate->delete();
            return redirect()->back()->with('message', 'candidate deleted');
        } catch (\Exception $e) {
        }
    }
}

resources/views/jobs/show.blade.php
@extends('layouts.app')

@section('content')

    <!-- Titlebar
================================================== -->
    <div class="single-page-header" data-background-image="{{ asset('images/single-job.jpg') }}">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="single-page-header-inner">
                        <div class="left-side">
                            <div class="header-image"><a href="{{ route('companies.show',$job->company->id) }}">
                                    <img src="{{ $job->company->image() }}" alt=""></a></div>
                            <div class="header-details">
                                <h3>{{ $job->title }}</h3>
                                <h5>{{ __('front.jobs.show.About the Employer') }}</h5>
                                <ul>
                                    <li>
                                        <a href="{{ route('companies.show',$job->company->id) }}">
                                            <i class="icon-material-outline-business"></i>{{ $job->company->name }}</a>
                                    </li>
                                    {{--<li>
                                        <div class="star-rating" data-rating="4.9"></div>
                                    </li>--}}
                                    <li>{{ $job->company->location }}</li>
                                    {{--<li>
                                        <div class="verified-badge-with-title">Verified</div>
                                    </li>--}}
                                </ul>
                            </div>
                        </div>
                        @if($job->salary_min or $job->salary_man)
                            <div class="right-side">
                                <div class="salary-box">
                                    <div class="salary-type">{{ __('front.jobs.show.Salary') }}</div>
                                    @if($job->salary_min && $job->salary_man)
                                        <div class="salary-amount">{{ $job->salary_min }} - {{ $job->salary_max }}DZD
                                        </div>
                                    @else
                                        @if($job->salary_min)
                                            <div class="salary-amount">{{ $job->salary_min }} DZD</div>
                                        @else
                                            <div class="salary-amount">{{ $job->salary_mxn }} DZD</div>
                                        @endif
                                    @endif
                                </div>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Page Content
    ================================================== -->
    <div class="container">
        <div class="row">

            <!-- Content -->
            <div class="col-xl-8 col-lg-8 content-right-offset">

                <div class="single-page-section">
                    <h3 class="margin-bottom-25">{{ __('front.jobs.show.Job Description') }}</h3>
                    {!! html_entity_decode($job->description) !!}
                </div>

                <div class="single-page-section">
                    <h3 class="margin-bottom-30">{{ __('front.jobs.show.Location') }}</h3>
                    <div id="single-job-map-container">
                        <div id="singleListingMap" data-latitude="{{ $job->lat }}" data-longitude="{{ $job->lng }}"
                             data-map-icon="im im-icon-Hamburger"></div>
                        <a href="#" id="streetView">Street View</a>
                    </div>
                </div>

                <div class="single-page-section">
                <!--
                    <h3 class="margin-bottom-25">{{ __('front.jobs.show.Similar Jobs') }}</h3>
-->
                    <!-- Listings Container -->
                    <div class="listings-container grid-layout">

                    @foreach($job->similarJobs() as $similarJob)
                        <!-- Job Listing -->
                            <a href="{{ route('jobs.show', $similarJob->id) }}" class="job-listing">

                                <!-- Job Listing Details -->
                                <div class="job-listing-details">
                                    <!-- Logo -->
                                    <div class="job-listing-company-logo">
                                        <img src="{{ $similarJob->company->image() }}" alt="">
                                    </div>

                                    <!-- Details -->
                                    <div class="job-listing-description">
                                        <h4 class="job-listing-company">{{ $similarJob->company->name }}</h4>
                                        <h3 class="job-listing-title">{{ $similarJob->title }}</h3>
                                    </div>
                                </div>

                                <!-- Job Listing Footer -->
                                <div class="job-listing-footer">
                                    <ul>
                                        <li><i class="icon-material-outline-location-on"></i>{{ $similarJob->location }}
                                        </li>
                                        <li><i class="icon-material-outline-business-center"></i>{{ $similarJob->type }}
                                        </li>
                                        <li>
                                            <i class="icon-material-outline-access-time"></i>{{ $similarJob->created_at->diffForHumans() }}
                                        </li>
                                    </ul>
                                </div>
                            </a>
                        @endforeach

                    </div>
                    <!-- Listings Container / End -->

                </div>
            </div>

            <!-- Sidebar -->
            <div class="col-xl-4 col-lg-4">
                <div class="sidebar-container">

                    @guest()

                        <a href="{{ route('register') }}?job={{ $job->id }}" class="apply-now-button">
                            Postuler <i class="icon-material-outline-arrow-right-alt"></i>
                        </a>

                    @else
                        @if($candidate)
                            <a href="{{ route('dashboard.candidates.edit', $candidate->id) }}"
                               class="apply-now-button " style="background-color: #38b653">
                                Visualiser candidature <i class="icon-material-outline-check-circle"></i>
                            </a>
                        @else
                            @if(!Auth::user()->employer)
                            <a href="{{ route('dashboard.candidates.store') }}" onclick="event.preventDefault();
                                                     document.getElementById('apply-form').submit();" class="apply-now-button">
                                Postuler <i class="icon-material-outline-arrow-right-alt"></i>
                            </a>
                            <form id="apply-form" action="{{ route('dashboard.candidates.store') }}" method="POST" style="display: none;">
                                @csrf
                                <input type="hidden" name="job" value="{{ $job->id }}">
                            </form>
                            @endif
                        @endif

                    @endguest

                    <!-- Sidebar Widget -->
                    <div class="sidebar-widget">
                        <div class="job-overview">
                            <div class="job-overview-headline">{{ __('front.jobs.show.Job Summary') }}</div>
                            <div class="job-overview-inner">
                                <ul>
                                    <li>
                                        <i class="icon-material-outline-location-on"></i>
                                        <span>{{ __('front.jobs.show.Location') }}</span>
                                        <h5>{{ $job->location }}</h5>
                                    </li>
                                    <li>
                                        <i class="icon-material-outline-business-center"></i>
                                        <span>{{ __('front.jobs.show.Job Type') }}</span>
                                        <h5>{{ $job->type }}</h5>
                                    </li>
                                    <li>
                                        <i class="icon-material-outline-local-atm"></i>
                                        <span>{{ __('front.jobs.show.Salary') }}</span>
                                        <h5>
                                            @if($job->salary_min or $job->salary_man)
                                                @if($job->salary_min && $job->salary_man)
                                                    {{ $job->salary_min }} - {{ $job->salary_max }}DZD
                                                @else
                                                    @if($job->salary_min)
                                                        {{ $job->salary_min }} DZD
                                                    @else
                                                        {{ $job->salary_mxn }} DZD
                                                    @endif
                                                @endif
                                            @endif
                                        </h5>
                                    </li>
                                    <li>
                                        <i class="icon-material-outline-access-time"></i>
                                        <span>{{ __('front.jobs.show.Date Posted') }}</span>
                                        <h5>{{ $job->created_at->diffForHumans() }}</h5>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <!-- Sidebar Widget -->
                    <div class="sidebar-widget">
                        <h3>{{ __('front.jobs.show.Bookmark or Share') }}</h3>

                        <!-- Bookmark Button -->
                        <book-mark
                            class="margin-bottom-25"
                            show-button
                            id="{{ $job->bookmark() ? $job->bookmark()->id : '' }}"
                            model-id="{{ $job->id }}"
                            model-type="job"
                            add-route="{{ route('dashboard.bookmarks.store') }}"
                            remove-route="{{ route('dashboard.bookmarks.destroy','_id_' ) }}"
                        ></book-mark>

                        <!-- Copy URL -->
                        <div class="copy-url">
                            <input id="copy-url" type="text" value="" class="with-border">
                            <button class="copy-url-button ripple-effect" data-clipboard-target="#copy-url"
                                    title="Copy to Clipboard" data-tippy-placement="top"><i
                                    class="icon-material-outline-file-copy"></i></button>
                        </div>

                        <!-- Share Buttons -->
                        <!--
                        <div class="share-buttons margin-top-25">
                            <div class="share-buttons-trigger"><i class="icon-feather-share-2"></i></div>
                            <div class="share-buttons-content">
                                <span>@lang('front.jobs.show.Interesting? Share It!')</span>
                                <ul class="share-buttons-icons">
                                    <li><a href="#" data-button-color="#3b5998" title="Share on Facebook"
                                           data-tippy-placement="top"><i class="icon-brand-facebook-f"></i></a></li>
                                    <li><a href="#" data-button-color="#1da1f2" title="Share on Twitter"
                                           data-tippy-placement="top"><i class="icon-brand-twitter"></i></a></li>
                                    <li><a href="#" data-button-color="#dd4b39" title="Share on Google Plus"
                                           data-tippy-placement="top"><i class="icon-brand-google-plus-g"></i></a></li>
                                    <li><a href="#" data-button-color="#0077b5" title="Share on LinkedIn"
                                           data-tippy-placement="top"><i class="icon-brand-linkedin-in"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        -->
                    </div>

                </div>
            </div>

        </div>
    </div>
@endsection

@section('after-js')

    <!-- Snackbar // documentation: https://www.polonel.com/snackbar/ -->
    <script>

    // Snackbar for copy to clipboard button
    $('.copy-url-button').click(function () {
        Snackbar.show({
            text: '{{ __('front.jobs.show.Copied to clipboard!') }}',
        })
    })
    </script>

    <script
        src="https://maps.googleapis.com/maps/api/js?key={{ config('google-maps.key') }}&libraries=places"></script>
    <script src="{{ asset('js/maps/infobox.min.js') }}"></script>
    <script src="{{ asset('js/markerclusterer.js') }}"></script>
    <script src="{{ asset('js/maps.js') }}"></script>
@endsection